### ISSUE TITLE
..-. .--.- .-.   .. -.- -.- .   -... . ... - .. .-.. -   ---. .-..

### ISSUE THREAD

**Issue by raflemakt** [sigurdo/morsekoder#1]
.... . ..   ... .. --. ..- .-. -.. --..--   .--- . --.   ... - .--.- .-.   .... . .-.   ..   -... .- .-. . -.   --- --.   .--. .-. ---. ...- . .-.   .--.-   -... . ... - .. .-.. .-.. .   ---. .-.. --..--   -- . -.   -... .- .-. - . -. -.. . .-. . -.   ... -.- .--- ---. -. -. . .-.   .. -. --. . -. - .. -. --.   ... .. -.. . -.   ... -.- .-. .. .--. - . -   .. -.- -.- .   ... - ---. - - . .-.   -... --- -.- ... - .- ...- . -.   ---.

**Comment by sigurdo** [comment]
-... . -.- .-.. .- --. . .-.     ..- .-.. . -- .--. . -. --..--     .--. .-. --- -... .-.. . -- . -     ... -.- .- .-..     ...- .-.- .-. .     ..-. .. -.- ... .-     -. .--.-     -- . -..     [.--. ..- .-.. .-..     .-. . --.- ..- . ... -     ..---](https://github.com/sigurdo/morsekoder/pull/2)
